name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements-dev.txt

      - name: Run tests
        env:
          PYTHONPATH: src
        run: pytest -q
